### ISSUE TITLE
Gnome 3 Notification Improvements

### ISSUE THREAD

**Issue by cwmke** [ion201/gnome-download-notify#1]
It would be great if notifications were able to be preserved in the gnome panel notification tray. Right now, notifications are shown and then disappear without stacking in the tray. Thanks for the great extension.

Edit: Realized this is just a problem with one site. Closed.

**Comment by ion201** [comment]
@cwmke In case you haven't seen it yet, there is an option in the addon preferences for this. If you set "transient notifications timing" to zero, they will always persist in the tray. It's the time which made it transient or not rather than the site.

**Comment by cwmke** [comment]
Thanks for the information. That solves it. 😁
