### ISSUE TITLE
Need 2 Vital Features

### ISSUE THREAD

**Issue by koolx** [ion201/gnome-download-notify#12]
Would you add 2 of these feature in Download Notifications?

1) Place the notification anywhere a user wants? 
2) Add a custom sound as to when the download has completed?

**Comment by ion201** [comment]
(1) will require changes I've been thinking about for #3 - to implement an html notification instead of using the host notification. I've generally not spent very much time looking at this because the native notifications on linux are very good.

(2) I think is very doable.

**Comment by koolx** [comment]
Hi.. when do you think you will be updating these needed changes?

**Comment by ion201** [comment]
I added some initial (incomplete) support for (2) in 467b09d1e3f13bb1aae98155375f9a711ef940f3 and 4e533468b259dc6b7d65b6104118717fe130ee2d. It will probably be a while before I consider the requirements for (1) in more detail.

**Comment by ion201** [comment]
Resolving old issue. 


> 1. Place the notification anywhere a user wants?

Complete

> 2. Add a custom sound as to when the download has completed?

Won't fix, I intend to stick to native notification integration, where this is not possible.
