### ISSUE TITLE
Can the icon be changed ? for a visual treat & open the file on clicking on notification

### ISSUE THREAD

**Issue by aahnik** [ion201/gnome-download-notify#14]
Hi @ion201  and @t1m0thyj , this extension is a life saver. I came to firefox from Chrome, and I was used to seeing a download status bar at bottom in chrome.

In firefox, the blue download icon animation is shown, but that does not attract my attention. 

> **This happened with me few times:**
> When I click on a link expecting it to open a new page, and it is a downloading something, i keep mistakenly clicking on it thinking a new page will open (as I did not notice the blue download icon animation). 

------

This extension, notifies me that a file has been downloaded.

- But the icon of firefox in the notification does not match the lates icon on Firefox, and it also appears somewhat hazy. Can this be changed for a better aesthetic ?

- Is it possible to open the downloaded file, when the notification is clicked ?

**Comment by aahnik** [comment]
[offtopic question] please help.

When I right click on an image, and click "Save image as" -> the file saver box appears 

![image](https://user-images.githubusercontent.com/66209958/106698648-3c746f80-6607-11eb-9578-4b5ea2abc12c.png)

it prompts me to save the file in `run/user/...`. But I want this box to open in a desired folder by default. How to do that ?

In chrome, it remembers the last choosen location. But in firefox, it always opens the same `run/user/..` location.

Thanks a lot for help.

**Comment by ion201** [comment]
> But the icon of firefox in the notification does not match the lates icon on Firefox, and it also appears somewhat hazy. Can this be changed for a better aesthetic ?

Simple enough to update the icon here, I hadn't noticed the difference yet. The new one is a bit cleaner so it ought to scale a bit better. I'm not sure what alternative would be more appropriate.

> Is it possible to open the downloaded file, when the notification is clicked ?

https://github.com/ion201/gnome-download-notify/issues/3#issuecomment-333345667

> it prompts me to save the file in run/user/.... But I want this box to open in a desired folder by default. How to do that ?

No idea, looks like a bug since the behavior should be the same as chrome.
