### ISSUE TITLE
ignore file types options.

### ISSUE THREAD

**Issue by circcc** [ion201/gnome-download-notify#16]
Please add,

1.ignore file types options.
for example, "jpg,png,gif,htm,html, ..."
Download Manager (S3) addon have this option.

2.Custom sound file option.
Notification Sound (https://addons.mozilla.org/en/firefox/addon/notification-sound/) addon have this option.

**Comment by ion201** [comment]
This is reasonable. I am thinking of adding (1) as an list similar to Download Manager (S3).  
The sound notification is admittedly a bit half-baked. I have considered adding a custom option before but it's more on my radar now.

**Comment by ion201** [comment]
https://github.com/ion201/gnome-download-notify/releases/tag/1.3.0
