### ISSUE TITLE
Clean install of the extension – nothing happens

### ISSUE THREAD

**Issue by tagawa** [ion201/gnome-download-notify#17]
**Environment:**
Firefox 96; macOS 11.6.1 (Big Sur)

**Extension version:**
1.3.0 (default preferences)

**Problem:**
When downloading a file (e.g. the linked zip file on this page: http://daniemon.com/blog/free-html5-template/ ), the download completes but no notification appears. I've given Firefox permission to show system notifications in macOS preferences, and restarted the browser, but no change. Any ideas?

**Comment by ion201** [comment]
I can't replicate the issue on my end; the defaults should allow all notifications without filtering. Please try the following debug steps:

Navigate to `about:devtools-toolbox?id=gnome-download-notify%40ion201&type=extension` in your browser and open the console tab. In the filter field at the top, type `main-webext.js`. Do any messages or errors pop up? Do you get any new messages or errors when a download completes?

**Comment by tagawa** [comment]
Thanks for the quick reply @ion201.

I tried that but there are no messages for main-webext.js. The only console entry is `buildWebpage() Skipping key: config_version` from `pref.js` but that seems unrelated. When a download completes, no new messages appear.

**Comment by ion201** [comment]
From the same console, you should be able to copy and paste the below line. This will send a simple test notification from the browser

```
browser.notifications.create('test', {'type': 'basic', 'title': 'TEST', 'message': 'this is a test'})
```

If you see the test notification, then I can look at some additional debug information to understand what is failing in the extension.

If you don't see the test notification, then you're probably missing a configuration option somewhere but I'm not familiar enough with mac to say what that might be.

**Comment by tagawa** [comment]
Sadly I don't get a test notification with that command, so it looks like something with my setup and not your extension. Sorry for the false alarm and thanks for helping investigate.

**Comment by ion201** [comment]
Resolving issue not reproducible.

**Comment by MikeRixWolfe** [comment]
~~I'm experiencing the same thing as tagawa, including the test notification not popping up, after upgrading to windows 11~~

@tagawa if you have windows notifications turned off, turning them on fixed this for me
