### ISSUE TITLE
Add audio-notification

### ISSUE THREAD

**Issue by Korb** [ion201/gnome-download-notify#18]
I suggest adding to this browser extension the ability to include not only visual, but also sound notifications about download completion. At a minimum, choose from several preset sounds, or even allow the user to select their own audio file.

**Comment by ion201** [comment]
In `about:addons`, select the "options" tab in the details page for the extension.

![Screenshot 2024-08-13 105118](https://github.com/user-attachments/assets/16e4f068-3b2c-4be8-87c5-89d6abeca645)
