### ISSUE TITLE
Addon won't work in Firefox 57+

### ISSUE THREAD

**Issue by airon90** [ion201/gnome-download-notify#2]
Addon isn't actually working on Firefox Nightly (alpha version of Firefox). The addon will work up to Firefox 56. Here is the news: https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing

**Comment by ion201** [comment]
Thank you for this reminder. I'm aware of this issue and just haven't gotten around to looking at the options for converting this to a webextension.

**Comment by ion201** [comment]
Ported to webextension with most recent commits. Version 1.0.0 should show up on AMO shortly.
