### ISSUE TITLE
Add a Play button for embedded (and custom) audio notifications

### ISSUE THREAD

**Issue by Korb** [ion201/gnome-download-notify#20]
At the current moment, when selecting any value in the "play an audio cue with every notification" field, there is no way to hear the signal sound without having to run a test download for this. In addition, with some extension settings, not every download will issue a notification and, accordingly, give the user the opportunity to hear the sound. Selecting a sound only by its name is a bad idea.

**Comment by ion201** [comment]
Added in 239b39e. Thank you for the suggestion
