### ISSUE TITLE
Notification icon gets pixelated on Plasma

### ISSUE THREAD

**Issue by rc2dev** [ion201/gnome-download-notify#4]
The icon resolution is too small for Plasma notifications.

![Screenshot.](https://user-images.githubusercontent.com/4497566/32146847-c6b5b57c-bcc4-11e7-8142-c6ee059d8c80.png)

Thanks for your work.

**Comment by ion201** [comment]
1.0.2 should show up in AMO soon enough. I updated the icon resolution from 16x16 to 48x48
