### ISSUE TITLE
Firefox icon should be updated

### ISSUE THREAD

**Issue by CaviaPorcellus** [ion201/gnome-download-notify#5]
When a download is completed the old Firefox icon appears in the notification. It should be updated with the [newer one](http://design.firefox.com/photon/images/product-identity-assets/firefox.png) (introduced in Firefox 57/Quantum). Tested with Firefox 57 on Ubuntu 16.04 if it matters.

Thanks.

**Comment by ion201** [comment]
Updated icon in 1.0.3. Thank you for pointing this out.
