### ISSUE TITLE
Extra download notification

### ISSUE THREAD

**Issue by CaviaPorcellus** [ion201/gnome-download-notify#6]
Sometimes a second notification for a single download appears.

After the initial notification, if the user clicks on the download icon (if placed in the navbar or wherever): then a second notification may appear. Unfortunately I can't consistently reproduce this, it just seems to happen randomly.

Here is me clicking on the download icon just as another download finished, so an old one appears as well at the same time (despite already having been displayed a while ago):
![screenshot from 2017-11-17 14-48-01](https://user-images.githubusercontent.com/5825551/32966087-a8a0b62c-cba6-11e7-8dfe-d37913d29192.png)

Tested with Firefox 57 on Ubuntu 16.04.

**Comment by ion201** [comment]
I've noticed this too. Fixed this in the original version (before switching to webextensions) so something got lost in translation there.

**Comment by ion201** [comment]
When a local file is deleted or moved, firefox sends a second event which I hadn't noticed before. Should be fixed in 1.0.3
