### ISSUE TITLE
Allow installation on Windows

### ISSUE THREAD

**Issue by Luke-Baker** [ion201/gnome-download-notify#7]
> This add-on is not available on your platform.

The AMO page shows the above message, along with a disabled "Add to Firefox" button.

> Windows and OSX should work if tested.

I've tested in Nightly 59 on Windows 10 x64 by faking the user agent string. A notification was displayed after a download completed. I think it's safe to allow Windows users to install this.

**Comment by ion201** [comment]
That's reasonable, I'll take another look at this.

**Comment by ion201** [comment]
1.0.4 is approved for all platforms on AMO
