### ISSUE TITLE
Option to only notify downloads that take more than a certain time

### ISSUE THREAD

**Issue by Homme-Nuage** [ion201/gnome-download-notify#8]
I don't need to be notified each image download, especially when I download a a series  of pictures. That's mainly why I disabled the animation of the download button. But I do need to be notified the completion of a long download.

If you could do that, you'd solve a problem I've had for a long time.

**Comment by ion201** [comment]
Since there is already an option to change the behavior based on the download time, this should be trivial to implement as an option when I have a chance to try it out.

**Comment by Homme-Nuage** [comment]
Cool, thanks.

**Comment by ion201** [comment]
Added an option to the preferences pane in 1.0.5 on AMO

**Comment by Homme-Nuage** [comment]
Thank you very much.
