### ISSUE TITLE
How to get night mode?

### ISSUE THREAD

**Issue by RheingoldRiver** [ion201/gnome-download-notify#9]
The screenshots are all night mode but for me it's displaying on a white background. I can change in userChrome but not sure what classes to change since I can't inspect it.

**Comment by ion201** [comment]
On linux the notification is integrated and themed by the desktop - the screenshots are arc-dark / numix with cinnamon.  On windows or OSX, I can't offer any useful advice for a dark theme since the webextension notification API is far removed from that aspect of the notification creation.

**Comment by RheingoldRiver** [comment]
Ah makes sense, thanks for the response!
